{
 "title": "Rahisi",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "READY NODES",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}) by (condition)"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "MEM USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\r\n  1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1- ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} ) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "% OF CPU LIMIT USED",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\"}[5m])) by (pod) /sum(container_spec_cpu_quota{ image!=\"\", container!=\"POD\"} /container_spec_cpu_period{ image!=\"\", container!=\"POD\"}) by (pod) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "% OF MEM LIMIT USED",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\"}) by (pod) )/ (sum(kube_pod_container_resource_limits{container!=\"POD\"}) by (pod) ) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU THROTTLED SECONDS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(\r\n    rate(container_cpu_cfs_throttled_seconds_total[5m])) \r\nby (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "% MEM USED BY EACH NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum( container_memory_working_set_bytes{container=\"\", namespace=~\".+\"} ) by (namespace) / ignoring (namespace) group_left sum( machine_memory_bytes{}) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "template",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}