apiVersion: v1
kind: LimitRange
metadata:
  name: CLUSTER_NAME-limit-range
spec:
  limits:
    - default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
